### ISSUE TITLE
Broken link in “Tokens on EVM chains”

### ISSUE THREAD

**Issue by lukaw3d** [LedgerHQ/developer-portal#120]
https://developers.ledger.com/docs/tokens/integrating-tokens/evm-chains-tokens
https://github.com/LedgerHQ/developer-portal/blob/2fd7cfb7577380fd617e7e61a6e1b706cb3e5e84/pages/docs/tokens/integrating-tokens/evm-chains-tokens.mdx#L14 link is broken

**Comment by cfranceschi-ledger** [comment]
Thank you for noticing it @lukaw3d. It is fixed.
