### ISSUE TITLE
How to locally build the portal?

### ISSUE THREAD

**Issue by jibeee** [LedgerHQ/developer-portal#210]
Build instructions have been removed in https://github.com/LedgerHQ/developer-portal/commit/859e1b6d66a495d14d6335cee6a013ad48b4ddf6. It was useful to run a test platform and check if documentation was correctly rendered.

Is it possible to revert this commit?

**Comment by cfranceschi-ledger** [comment]
Hi @jibeee, it has been decided that the instructions remain internal to Ledger for the moment.
