### ISSUE TITLE
Removed link

### ISSUE THREAD

**Issue by jibeee** [LedgerHQ/developer-portal#213]
Link has been removed during migration from RTD:
https://github.com/LedgerHQ/developer-portal/blob/79f13be5a820238ea7c312497dcab7887f7cf2a3/_docs/nano-app/psd-keys.md#L53

`hd_use_cases` should point to <https://developers.ledger.com/docs/nano-app/psd-applications/>.

**Comment by jibeee** [comment]
This does not fix anything. It just creates an empty link that points to nothing.

You can create a link like this:

```diff
diff --git a/_docs/nano-app/psd-keys.md b/_docs/nano-app/psd-keys.md
index 4ef9cc2..c16c767 100755
--- a/_docs/nano-app/psd-keys.md
+++ b/_docs/nano-app/psd-keys.md
@@ -50,7 +50,7 @@ For example, this model can be used to facilitate the process of auditing an HD

 For a more detailed list and explanation of some of the use-cases made possible by this model, see [this section](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#use-cases) of the BIP 32 specification.

-In the next section, `hd_use_cases`, we'll talk about how all of these features are used by HD wallets and other applications.
+In the [next section]({% link _docs/nano-app/psd-applications.md %}), we'll talk about how all of these features are used by HD wallets and other applications.

 <!--  -->
 {% include alert.html style="primary" text="If you'd like to play with BIP 39 mnemonics or BIP 32 derivation on a computer, take a look at this tool: <a href='https://iancoleman.io/bip39/' class='alert-link'> iancoleman.io/bip39 </a> " %}
```

Reference: <https://jekyllrb.com/docs/liquid/tags/#linking-to-posts>

Thanks!

**Comment by cfranceschi-ledger** [comment]
Sorry the problem in my PR was just that I forgot the link in the href.
FYI I could not use markdown formatting (` []() `) in that case because I needed to mix code and link SCSS properties and it only works with HTML. That is if we wanted `hd_use_cases` to be the link as you asked in your first message.
But it is true it makes more sense to put it on "next section".

**Comment by cfranceschi-ledger** [comment]
The link is now working.
