### ISSUE TITLE
Feedback for “Sections” Data-Driven Risk and Security Solutions 

### ISSUE THREAD

**Issue by VysochynYakov** [LedgerHQ/developer-portal#255]
Hey there, team Ledger!

My name is Yakov, and I represent Fyde. We are excited to introduce our new product that enables security **modeling and stress testing** of your new products and ideas.  

![Fyde partnership (7)](https://github.com/user-attachments/assets/9c1c7d92-3f31-4dd7-b8c9-50c5394549a9)

We work with EVM protocols and builders to simulate new ideas and product features before launch - making sure that everything is stress tested before released! 

We can help with everything from agent-based simulations, to optimising liquidity profiles, to stress testing tokenomics designs.   If you find this interesting, I would love to arrange a call to discuss it in more detail.  

Looking forward to your response.  

Best regards, 
Yakov

**Comment by cfranceschi-ledger** [comment]
Hello @VysochynYakov,
This is not the place to talk about partnerships. I'm closing the issue.
