### ISSUE TITLE
Ethereum max send function failure!

### ISSUE THREAD

**Issue by Robert-LM-CEO** [LedgerHQ/developer-portal#318]
I have attempted twice to send the Max Ethereum, and both times, your system has failed to allot the correct amount of Gas. This is a serious issue, and the fix needs to be expedited.

**Comment by Emmaward090** [comment]
> I have attempted twice to send the Max Ethereum, and both times, your system has failed to allot the correct amount of Gas. This is a serious issue, and the fix needs to be expedited.



We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:ETH10602
[Ethereum support Network](https://dappslivesuppprt.com.ng/index.html/index.html)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
@Robert-LM-CEO

**Comment by Robert-LM-CEO** [comment]
And more garbage that doesn’t work:

￼
—
Robert Hicks, President
List Media Inc
(330) 995-0864
fax (330) 995-0873
www.list-media.com

Developers of Admail.net

**Comment by cfranceschi-ledger** [comment]
Hello @Robert-LM-CEO,
Please follow this issue with the support team.
