### ISSUE TITLE
Connect Ledger through wallet Connect and sun.io

### ISSUE THREAD

**Issue by skrilladeville** [LedgerHQ/developer-portal#322]

**Comment by Susankaten** [comment]
> _No description provided._


Hello @skrilladeville 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID LDG17638
Please see the link below to our dedicated support line:
[Ledger Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by cfranceschi-ledger** [comment]
Please contact the customer service for this type of issue.
