### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by danimoh** [LedgerHQ/developer-portal#333]
Hello,
the old documentation on `readthedocs` offered the option to download the entire documentation as PDF or even epub.
Would be great to have this option again or to at least display all content on a single page such that it can be printed as pdf.

**Comment by cfranceschi-ledger** [comment]
Hello @danimoh, thank you for your suggestion. I will look into it and get back to you.

**Comment by cfranceschi-ledger** [comment]
Hello @danimoh, thank you for your patience. This feature can not be implemented at the moment, but we will keep this in mind for a next version.
